name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: [ '.github/**' ]

jobs:
  deploy:
    name: CD Lint, Test and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Prettier
      run: npm run prettier:check

    - name: Test
      run: npm run test:ci

    - name: Build and Deploy
      run: |
        git config --global user.email dino.sources.kadric@gmail.com
        git config --global user.name QualityPlastics
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/qualityplasticsltd.git
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/QualityPlastics/qualityplasticsltd.git
        npm run deploy
