name: Tests

on:
  pull_request:
    branches: [ master ]
    paths-ignore: [  ]

jobs:
  test:
    name: CI Lint and Test 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1

    - name: Install
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Prettier
      run: npm run prettier:check

    - name: Test
      run: npm run test:ci
